spring:
  thymeleaf:
    cache: false
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:     username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# log 配置
logging:
  file: logs/blog.log
  level:
    com:
      cxy:
        blog: debug